version: "3.8"

services:
  app:
    container_name: varastonhallintaexpress
    restart: always
    networks:
      - front
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    env_file:
      - .env
    links:
      - mongo
  nginx:
    image: nginx:latest
    restart: always
    container_name: production_nginx
    build:
      context: .
      dockerfile: Dockerfile-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - front
    links:
      - app
  mongo:
    image: 'bitnami/mongodb'
    environment:
      MONGODB_INITDB_ROOT_USERNAME: root
      MONGODB_INITDB_ROOT_PASSWORD: rootpassword
      MONGODB_ROOT_PASSWORD: password123
    ports:
      - 27017:27017
    volumes:
      - /mongo/mongo:/data/db
    networks:
      - front
  jenkins:
    image: 'bitnami/jenkins'
    ports:
      - '8081:8080'
      - '8443:8443'
      - '50000:50000'
    volumes:
      - 'jenkins_data:/bitnami/jenkins'

volumes:
  jenkins_data:
    driver: local

networks:
  front:
    driver: bridge
